# Test de bout en bout de Mémo J (client Supabase simulé)
import asyncio, os, subprocess, sys, datetime
from playwright.async_api import async_playwright

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
OUT = os.path.join(ROOT, 'tests', 'captures')
os.makedirs(OUT, exist_ok=True)
MOCK = open(os.path.join(ROOT, 'tests', 'mock-supabase.js'), encoding='utf-8').read()

async def main(theme='light'):
    srv = subprocess.Popen([sys.executable, '-m', 'http.server', '8765', '--directory', ROOT], stdout=subprocess.DEVNULL, stderr=subprocess.DEVNULL)
    await asyncio.sleep(1)
    errors = []
    async with async_playwright() as p:
        b = await p.chromium.launch()
        ctx = await b.new_context(viewport={'width': 390, 'height': 844}, device_scale_factor=2, color_scheme=theme, locale='fr-FR', timezone_id='Europe/Paris')
        page = await ctx.new_page()
        page.on('console', lambda m: errors.append(m.text) if m.type == 'error' else None)
        page.on('pageerror', lambda e: errors.append(str(e)))
        await page.route('**/vendor/supabase.js', lambda r: r.fulfill(status=200, content_type='application/javascript', body=MOCK))
        await page.route('https://fonts.googleapis.com/**', lambda r: r.fulfill(status=200, content_type='text/css', body=''))
        await page.goto('http://localhost:8765/index.html')
        await page.wait_for_selector('#form-auth')
        sfx = '' if theme == 'light' else '-sombre'
        await page.screenshot(path=f'{OUT}/01-connexion{sfx}.png')
        await page.fill('#email', 'vincent@example.com'); await page.fill('#mdp', 'motdepasse123')
        await page.click('button[data-mode=connexion]')
        await page.wait_for_selector('text=Bienvenue dans Mémo J')
        await page.click('button[data-action=nouvelle-matiere]')
        await page.wait_for_selector('#nom-m')
        await page.fill('#nom-m', 'Droit bancaire')
        await page.select_option('#semaine', index=12)
        await page.wait_for_timeout(500)
        await page.screenshot(path=f'{OUT}/02-nouvelle-matiere{sfx}.png')
        await page.click('#ok')
        await page.wait_for_timeout(600)
        # deuxième matière avec couleur perso
        await page.click('button[data-action=nouvelle-matiere]')
        await page.fill('#nom-m', 'Mathématiques financières')
        await page.click('[data-couleur=perso]')
        await page.fill('#hex', '#12a150')
        await page.wait_for_timeout(400)
        await page.screenshot(path=f'{OUT}/03-couleur-perso{sfx}.png')
        await page.click('#ok'); await page.wait_for_timeout(600)
        # chapitre commencé il y a 12 jours
        j0 = (datetime.date.today() - datetime.timedelta(days=12)).isoformat()
        await page.click('.acc-body button[data-action=nouveau-chapitre] >> nth=0')
        await page.wait_for_selector('#nom-c')
        await page.fill('#nom-c', 'Ch. 3 · Le crédit'); await page.fill('#j0', j0)
        await page.dispatch_event('#j0', 'change')
        await page.wait_for_timeout(500)
        await page.screenshot(path=f'{OUT}/04-nouveau-chapitre{sfx}.png')
        await page.click('#ok'); await page.wait_for_timeout(600)
        # un chapitre du jour
        await page.click('.acc-body button[data-action=nouveau-chapitre] >> nth=0')
        await page.fill('#nom-c', 'Ch. 4 · Les moyens de paiement'); await page.click('#ok'); await page.wait_for_timeout(600)
        await page.screenshot(path=f'{OUT}/05-matieres{sfx}.png')
        # Aujourd'hui : le Ch. 3 est en retard (J1)
        await page.goto('http://localhost:8765/index.html#/aujourdhui'); await page.wait_for_timeout(800)
        await page.screenshot(path=f'{OUT}/06-aujourdhui{sfx}.png')
        # valider le J1 en « encore frais »
        await page.click('button[data-valider] >> nth=0'); await page.wait_for_selector('#opts')
        await page.wait_for_timeout(500)
        await page.screenshot(path=f'{OUT}/07-validation{sfx}.png')
        await page.click('#ok'); await page.wait_for_timeout(800)
        # ajouter des révisions passées via le chapitre
        chid = await page.evaluate("window.__db.chapitres.find(c => c.nom.includes('crédit')).id")
        await page.goto(f'http://localhost:8765/index.html#/chapitre/{chid}?from=matieres'); await page.wait_for_timeout(1400)
        await page.screenshot(path=f'{OUT}/08-chapitre-semaines{sfx}.png', full_page=True)
        for ech in ['jours', 'mois']:
            await page.click(f'button[data-echelle={ech}]'); await page.wait_for_timeout(1400)
            await page.screenshot(path=f'{OUT}/09-chapitre-{ech}{sfx}.png')
        await page.click('button[data-action=ajouter-revision]'); await page.wait_for_timeout(500)
        await page.screenshot(path=f'{OUT}/10-revision-passee{sfx}.png')
        await page.click('[data-close] >> nth=1'); await page.wait_for_timeout(400)
        # semaine, stats, réglages
        await page.goto('http://localhost:8765/index.html#/semaine'); await page.wait_for_timeout(800)
        await page.screenshot(path=f'{OUT}/11-semaine{sfx}.png')
        await page.click('button[data-planifier] >> nth=0'); await page.wait_for_timeout(500)
        await page.screenshot(path=f'{OUT}/12-planifier{sfx}.png')
        for per in ['semaine', 'mois', 'semestre']:
            await page.goto('http://localhost:8765/index.html#/stats'); await page.wait_for_timeout(300)
            await page.click(f'button[data-periode={per}]'); await page.wait_for_timeout(800)
            await page.screenshot(path=f'{OUT}/13-stats-{per}{sfx}.png')
        await page.click('a[href^="#/stats/"] >> nth=0'); await page.wait_for_timeout(700)
        await page.screenshot(path=f'{OUT}/14-stats-matiere{sfx}.png')
        await page.click('a[href^="#/chapitre/"] >> nth=0'); await page.wait_for_timeout(900)
        back = await page.get_attribute('main a.link', 'href')
        print('retour depuis stats ->', back)
        await page.goto('http://localhost:8765/index.html#/reglages'); await page.wait_for_timeout(700)
        await page.screenshot(path=f'{OUT}/15-reglages{sfx}.png', full_page=True)
        # archiver puis restaurer
        await page.goto('http://localhost:8765/index.html#/matieres'); await page.wait_for_timeout(500)
        page.on('dialog', lambda d: asyncio.ensure_future(d.accept()))
        await page.click('button[data-archiver] >> nth=0'); await page.wait_for_timeout(600)
        await page.click('button[data-action=toggle-archives]'); await page.wait_for_timeout(500)
        await page.screenshot(path=f'{OUT}/16-archives{sfx}.png')
        state = await page.evaluate("({m: window.__db.matieres.map(m => [m.nom, !!m.archivee_le]), c: window.__db.chapitres.map(c => [c.nom, c.prochaine_date, c.prochain_j, c.facteur]), r: window.__db.revisions.map(r => [r.note, r.j_label])})")
        print(state)
        await b.close()
    srv.terminate()
    print('ERREURS CONSOLE:', errors if errors else 'aucune')

asyncio.run(main(sys.argv[1] if len(sys.argv) > 1 else 'light'))
